package com.powersteeringsoftware.core.objects.permissions.define_categories.workitems;


/**
 * This enum represents permissions on the page Admin>>Definó Categories for
 * permission category "Work Item"
 *
 * @author selyaev_ag
 *
 * @since 2009 August 6
 *
 */
public enum WorkItemsPermissionsEnum{
	VIEW("VIEW"),
	EDIT("EDIT"),
	DELETE("DELETE"),
	VIEW_PERMISSIONS("VIEW PERMISSIONS"),
	EDIT_PERMISSIONS("EDIT PERMISSIONS"),
	VIEW_DISCUSSION("VIEW DISCUSSION"),
	VIEW_HISTORY("VIEW HISTORY"),
	VIEW_ASSOCIATED_METRICS("VIEW ASSOCIATED METRICS"),
	VIEW_METRIC_ON_WORK_SUMMARY("VIEW METRIC ON WORK SUMMARY "),
	ADD_METRIC("ADD METRIC"),
	REMOVE_METRIC("REMOVE METRIC"),
	EDIT_TAGS("EDIT TAGS"),
	ARCHIVE("ARCHIVE"),
	DELEGATE("DELEGATE "),
	MOVE("MOVE"),
	EDIT_STATUS("EDIT STATUS"),
	ADD_DISCUSSION_ITEM("ADD DISCUSSION ITEM"),
	VIEW_RISKS("VIEW RISKS"),
	CREATE_RISKS("CREATE RISKS"),
	EDIT_RISKS("EDIT RISKS"),
	MAKE_AN_ISSUE("MAKE AN ISSUE"),
	REMOVE_ISSUES("REMOVE ISSUES"),
	VIEW_DOCUMENTS("VIEW DOCUMENTS"),
	ADD_DOCUMENT("ADD DOCUMENT"),
	EDIT_DOCUMENT("EDIT DOCUMENT"),
	DELETE_DOCUMENT("DELETE DOCUMENT"),
	EDIT_DOCUMENT_APPROVAL_SETTINGS("EDIT DOCUMENT APPROVAL SETTINGS"),
	ADD_TEAM_MEMBER("ADD TEAM MEMBER"),
	REMOVE_TEAM_MEMBER("REMOVE TEAM MEMBER"),
	EDIT_PRIORITY("EDIT PRIORITY"),
	VIEW_WORK_BREAKDOWN("VIEW WORK BREAKDOWN"),
	EDIT_WORK_BREAKDOWN("EDIT WORK BREAKDOWN"),
	EDIT_CONTROLS("EDIT CONTROLS"),
	VIEW_COST("VIEW COST"),
	EDIT_COST("EDIT COST"),
	EDIT_ACTUAL_SCHEDULE("EDIT ACTUAL SCHEDULE"),
	OVERRIDE_BASELINE_DATES("OVERRIDE BASELINE DATES"),
	EDIT_CONSTRAINT_DATES("EDIT CONSTRAINT DATES"),
	ADD_CHILD("ADD CHILD"),
	EDIT_RESOURCES_ALLOCATION("EDIT RESOURCES ALLOCATION"),
	ADD_ACTION_ITEM("ADD ACTION ITEM"),
	REQUEST_APPROVAL_OF_IDEA("REQUEST APPROVAL OF IDEA"),
	APPROVE_REJECT_IDEA("APPROVE / REJECT IDEA"),
	APPROVE_REJECT_BEST_PRACTICE_NOMINATION("APPROVE/REJECT BEST PRACTICE NOMINATION"),
	EXPAND_IDEA("EXPAND IDEA"),
	VIEW_STATUS_REPORTS("VIEW STATUS REPORTS"),
	APPROVE_REJECT_TIME("APPROVE/REJECT TIME"),
	EDIT_ELECTRONIC_SIGNATURE_SETTINGS("EDIT ELECTRONIC SIGNATURE SETTINGS"),
	UPDATE_METRIC_NUMBERS("UPDATE METRIC NUMBERS"),
	SET_READY_FOR_ROLL_UP("SET READY FOR ROLL-UP"),
	LOCK_METRICS("LOCK METRICS"),
	CHANGE_PHASE("CHANGE PHASE"),
	COPY_ATTACH_MEASURE("COPY/ATTACH MEASURE"),
	EDIT_MEASURE_HISTORY("EDIT MEASURE HISTORY"),
	SET_DELIVERABLE_FLAG("SET DELIVERABLE FLAG"),
	VIEW_PROJECT_REPORTS("VIEW PROJECT REPORTS"),
	CREATE_PROJECT_REPORTS("CREATE PROJECT REPORTS"),
	ASSIGN_CHAMPION("ASSIGN CHAMPION"),
	RE_ACTIVATE_GATE("RE-ACTIVATE GATE"),
	EDIT_RESOURCE_NEEDS("EDIT RESOURCE NEEDS"),
	ASSIGN_USERS_TO_RESOURCE_NEEDS("ASSIGN USERS TO RESOURCE NEEDS"),
	MASS_DELEGATE_WORK("MASS DELEGATE WORK");

	private String text;


	WorkItemsPermissionsEnum(String _text){
		text = _text;
	}

	public String getText() {
		return text;
	}
}
