# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1418120572);
user_pref("app.update.lastUpdateTime.background-update-timer", 1418120332);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1418120692);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1418120812);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1418120452);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1391197236);
user_pref("app.update.migrated.updateDir", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.update", false);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20141027150301");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 2630);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20141027150301");
user_pref("browser.startup.homepage_override.mstone", "33.0.2");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":3}");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.taskbar.lastgroupid", "D2B4E24BBDCD49BC");
user_pref("browser.uitour.whitelist.add.260", "");
user_pref("browser.uitour.whitelist.add.340", "");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1418120337901");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1418120341174");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1418206741174");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAccepted", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1418120275964");
user_pref("datareporting.policy.dataSubmissionPolicyResponseTime", "1418120306657");
user_pref("datareporting.policy.dataSubmissionPolicyResponseType", "accepted-info-bar-dismissed");
user_pref("datareporting.policy.firstRunTime", "1391197115924");
user_pref("datareporting.sessions.current.activeTicks", 7);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 2717);
user_pref("datareporting.sessions.current.main", 214);
user_pref("datareporting.sessions.current.sessionRestored", 2993);
user_pref("datareporting.sessions.current.startTime", "1418121267898");
user_pref("datareporting.sessions.current.totalTime", 36);
user_pref("datareporting.sessions.currentIndex", 4);
user_pref("datareporting.sessions.previous.2", "{\"s\":1418120209351,\"a\":90,\"t\":698,\"c\":true,\"m\":262,\"fp\":1657,\"sr\":4559}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1418120913935,\"a\":13,\"t\":62,\"c\":true,\"m\":208,\"fp\":2184,\"sr\":2349}");
user_pref("datareporting.sessions.prunedIndex", 1);
user_pref("dom.mozApps.used", true);
user_pref("dom.w3c_touch_events.expose", false);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:33.0.2");
user_pref("extensions.getAddons.cache.lastUpdate", 1418120212);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"winreg-app-global\",\"addons\":{\"wrc@avast.com\":{\"descriptor\":\"C:\\\\Program Files\\\\AVAST Software\\\\Avast\\\\WebRep\\\\FF\",\"mtime\":1407342320728,\"rdfTime\":1407342306770}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox 33.0\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1415221931221,\"rdfTime\":1414452950000}}}]");
user_pref("extensions.lastAppVersion", "33.0.2");
user_pref("extensions.lastPlatformVersion", "33.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/plugin");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.update.autoUpdateDefault", false);
user_pref("extensions.update.enabled", false);
user_pref("gecko.buildID", "20141027150301");
user_pref("gecko.mstone", "33.0.2");
user_pref("gfx.direct3d.last_used_feature_level_idx", 0);
user_pref("gfx.direct3d.prefer_10_1", true);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.database.lastMaintenance", 1418120339);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("security.default_personal_cert", "Select Automatically");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1418121268);
user_pref("toolkit.telemetry.previousBuildID", "20141027150301");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1393789121);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
