/**
 * 
 */
package com.powersteeringsoftware.core.objects.measures;

public enum MeasureEditPageFieldTypesEnum{
	NAME ("NAME"),
	DESCRIPTION("DESCRIPTION"),
	UNIT("UNIT"),

	DATA_COLLECTION("DATA_COLLECTION"),
	DISPLAY_FORMAT("DISPLAY_FORMAT"),
	EFFECTIVE_DATES("EFFECTIVE_DATES"),
	//for formula only
	FORMULA("FORMULA"),
	EVALUATE_AS("EVALUATE_AS"),
	TEST_SCHEDULE("TEST_SCHEDULE"),
	HISTORY_SCHEDULE("HISTORY_SCHEDULE"),
	//for goal only
	REMINDER_SCHEDULE("REMINDER_SCHEDULE"),
	INDICATOR_TYPE("INDICATOR_TYPE"),
	// for goal only
	START_DATE("START_DATE"),
	TARGET_DATE("TARGET_DATE"),
	TARGET_VALUE("TARGET_VALUE"),
	GOAL_MESSAGE_RED("GOAL_MESSAGE_RED"),
	GOAL_MESSAGE_YELLOW("GOAL_MESSAGE_YELLOW"),
	GOAL_MESSAGE_GREEN("GOAL_MESSAGE_GREEN"),
	GOAL_THRESHOLD_1("GOAL_THRESHOLD_1"),
	GOAL_THRESHOLD_2("GOAL_THRESHOLD_2"),
	//for variance only
	VARIANCE_MESSAGE_RED_1("VARIANCE_MESSAGE_RED_1"),
	VARIANCE_MESSAGE_RED_2("VARIANCE_MESSAGE_RED_2"),
	VARIANCE_MESSAGE_YELLOW_1("VARIANCE_MESSAGE_YELLOW_1"),
	VARIANCE_MESSAGE_YELLOW_2("VARIANCE_MESSAGE_YELLOW_2"),
	VARIANCE_MESSAGE_GREEN_1("VARIANCE_MESSAGE_GREEN_1"),
	VARIANCE_MESSAGE_GREEN_2("VARIANCE_MESSAGE_GREEN_2"),
	VARIANCE_THRESHOLD_1("VARIANCE_THRESHOLD_1"),
	VARIANCE_THRESHOLD_2("VARIANCE_THRESHOLD_2"),
	VARIANCE_THRESHOLD_3("VARIANCE_THRESHOLD_3"),
	VARIANCE_THRESHOLD_4("VARIANCE_THRESHOLD_4");

	private String name;

	MeasureEditPageFieldTypesEnum(String aName){
		this.name = aName;
	}

	public String getName(){
		return this.name;
	}
}